services:
  - type: web
    name: portal-educa-api
    env: node
    plan: free
    rootDir: api
    buildCommand: cd api && npm install
    startCommand: cd api && node server.js
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyCqENZk9QG7d_S4I77kYgmHZbOXeNe0X-k
      - key: NODE_ENV
        value: production

