services:
  - type: web
    name: portal-educa-api
    runtime: node
    plan: free
    rootDir: api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyCqENZk9QG7d_S4I77kYgmHZbOXeNe0X-k
      - key: NODE_ENV
        value: production

